"""Alembic environment. Targets Postgres 16 + PostGIS only (ADR 0003); reads `DATABASE_URL` from
the environment (CLAUDE.md). There is no SQLite fallback for running this migration — this
sprint's tests exercise the ORM models directly against SQLite instead (services/README.md).
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

import services.db.models  # noqa: F401 — registers tables on Base.metadata
from services.db.base import Base

config = context.config
if config.config_file_name is not None:
    # Keep already-created loggers alive: the default disables every existing logger, which
    # silently broke a billing test's caplog whenever migrations ran first (QA audit 2026-09-18).
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    config.set_main_option("sqlalchemy.url", DATABASE_URL)


#: `target_metadata` is passed to `context.configure(...)` only when generating a migration
#: (`alembic revision --autogenerate`), never for `upgrade`/`downgrade`/`stamp` (2026-09-18, ADR
#: 0008 backend lane). Every migration in this repo is hand-written, not autogenerated, so this
#: costs no capability the repo actually uses; passing it unconditionally used to make
#: `op.batch_alter_table(...)`'s `drop_constraint`/`create_check_constraint` calls silently
#: double-apply `Base.metadata`'s naming convention to an already-fully-named constraint (e.g.
#: turning `"ck_location_precision_vocab"` into `"ck_location_ck_location_precision_vocab"`,
#: reproduced with a minimal `MigrationContext.configure(conn, opts={"target_metadata": ...})`
#: repro) — the exact construct migrations 0009 and 0011 need for their `CHECK`/column changes on
#: SQLite. Autogenerate is unaffected: `config.cmd_opts` only carries an `autogenerate` attribute
#: when the `alembic revision --autogenerate` command set it up.
_AUTOGENERATE = bool(getattr(config.cmd_opts, "autogenerate", False))
_CONFIGURE_METADATA = target_metadata if _AUTOGENERATE else None


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=_CONFIGURE_METADATA,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=_CONFIGURE_METADATA)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
