"""`event.seq`: move the identity's sequence past every stored value (audit A5, 2026-09-30).

Migration 0001 declares `event.seq` as `bigint GENERATED BY DEFAULT AS IDENTITY`. Until
2026-09-30 an ORM `before_insert` listener (`services/db/models.py::_assign_event_seq`) supplied
`MAX(seq)+1` on every insert, on Postgres as well as SQLite. Postgres accepts a supplied value
for a BY DEFAULT identity, so the sequence behind it was never called. Measured on a copy of the
audit store: `event_seq_seq last_value=1, is_called=false` with `max(seq)=981`.

From this revision the listener runs on SQLite only, and on Postgres the sequence assigns `seq`.
A database written by the old code would then hand out 1, 2, 3... and collide with stored rows.
This revision moves the sequence so its next value is above both `max(seq)` and any value it
already handed out. It never moves the sequence backwards. On an empty table it is reset so the
first value is 1.

Deploy order: run it while no pre-0027 writer is running. The old code computes `MAX(seq)+1`
without the sequence, so an old writer and a new writer running together can still take the
same value. (`docs/60` deploys by stopping the stack, migrating, then starting it.)

Downgrade does nothing. The pre-0027 code never reads the sequence, so a sequence left ahead of
the data is harmless to it, and moving it back could hand out a value an open transaction holds.

SQLite has no sequences: both directions are no-ops there. The SQLite round-trip tests stamp an
earlier revision and walk to head, so this must not fail on SQLite or on a baseline without
`event`.

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0027"
down_revision: str | None = "0026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    if not sa.inspect(bind).has_table("event"):
        return
    sequence = bind.execute(sa.text("SELECT pg_get_serial_sequence('event', 'seq')")).scalar()
    if sequence is None:
        # Not an identity or serial column: nothing assigns `seq` in the database to repair.
        return
    max_seq = bind.execute(sa.text("SELECT max(seq) FROM event")).scalar()
    handed_out = bind.execute(
        sa.text("SELECT pg_sequence_last_value(CAST(:s AS regclass))"), {"s": sequence}
    ).scalar()
    high = max(int(max_seq or 0), int(handed_out or 0))
    if high == 0:
        bind.execute(sa.text("SELECT setval(CAST(:s AS regclass), 1, false)"), {"s": sequence})
    else:
        bind.execute(sa.text("SELECT setval(CAST(:s AS regclass), :v, true)"), {"s": sequence, "v": high})


def downgrade() -> None:
    """No-op: see the module docstring."""
